In [3]:
import pandas as pd

In [20]:
df = pd.read_csv('data/companies.csv')
print(df.shape)
df.head()

(4844, 12)

,Unnamed: 0,id,name,slug,website,smallLogoUrl,oneLiner,longDescription,teamSize,url,batch,status
0,0,379,Reddit,reddit,http://reddit.com,https://bookface-images.s3.amazonaws.com/small...,The frontpage of the internet.,Founded by Steve Huffman and Alexis Ohanian in...,2000.0,https://www.ycombinator.com/companies/reddit,S05,Acquired
1,1,378,Kiko,kiko,http://kiko.com,https://bookface-images.s3.amazonaws.com/small...,We're the best online calendar solution to eve...,Kiko is a web calendar for anyone who wants to...,0.0,https://www.ycombinator.com/companies/kiko,S05,Acquired
2,2,375,Clickfacts,clickfacts,http://clickfacts.com,NaN,NaN,ClickFacts is a Malware Software Solutions com...,11.0,https://www.ycombinator.com/companies/clickfacts,S05,Acquired
3,3,374,TextPayMe,textpayme,http://textpayme.com,NaN,NaN,"Founded in 2005, TextPayMe is an SMS payment s...",11.0,https://www.ycombinator.com/companies/textpayme,S05,Acquired
4,4,373,Loopt,loopt,http://loopt.com,https://bookface-images.s3.amazonaws.com/small...,NaN,"Loopt, based in Silicon-Valley and backed by l...",11.0,https://www.ycombinator.com/companies/loopt,S05,Acquired

In [16]:
unique_counts = df.nunique()
print(unique_counts)

Unnamed: 0         4844
id                 4844
name               4783
slug               4841
website            4812
smallLogoUrl       4197
oneLiner           4692
longDescription    4507
teamSize            194
url                4844
batch                39
status                4
dtype: int64

In [ ]:
nan_count_per_column = df.isna().sum()

print(nan_count_per_column)

Unnamed: 0           0
id                   0
name                 0
slug                 3
website             27
smallLogoUrl       647
oneLiner           152
longDescription    335
teamSize            78
url                  0
batch                0
status               0
dtype: int64

In [19]:
import csv

with open("data/regions.csv") as csvf:  
    regions = list(csv.DictReader(csvf))
    company_to_region_id = {}
    address_to_region_id = []
    
    for row in regions:
        if row["address"] not in address_to_region_id:
            address_to_region_id.append(row["address"])
    
    print(address_to_region_id)
    
    for row in regions:
        company_to_region_id[row["id"]] = str(address_to_region_id.index(row["address"]) + 1)
    
    print(company_to_region_id)

['San Francisco, CA, USA', 'Cambridge, MA, USA', 'Redmond, WA, USA', 'Mountain View, CA, USA', 'London, UK', 'Somerville, MA, USA', 'Wallingford, CT 06492, USA', 'New York, NY, USA', 'Palo Alto, CA, USA', 'Boston, MA, USA', '', 'Seattle, WA, USA', 'Tampa, FL, USA', 'Bethesda, MD, USA', '1737 Haight St, San Francisco, CA 94117, USA', 'Chicago, IL, USA', 'Oyster Bay, NY, USA', 'Santa Clara, CA, USA', 'Corvallis, OR, USA', 'Akron, OH, USA', 'Burlingame, CA, USA', 'Hoxton, London, UK', 'Southfield, MI, USA', 'Watertown, MA, USA', 'Atherton, CA 94027, USA', 'Vancouver, BC, Canada', 'Los Angeles, CA, USA', 'Atlanta, GA, USA', 'Copenhagen, Denmark', 'Portland, OR, USA', 'Lucerne Valley, CA 92356, USA', 'Columbia, MD, USA', 'Brooklyn, NY, USA', 'Princeton, NJ, USA', 'California, USA', 'Redwood City, CA, USA', 'Ann Arbor, MI, USA', 'Minneapolis, MN, USA', 'Austin, TX, USA', 'Santa Monica, CA, USA', 'Dublin, Ireland', 'San Carlos, CA, USA', 'Missoula, MT, USA', 'Columbus, OH, USA', 'Cupertino, CA, USA', 'Stockholm, Sweden', 'Montreal, QC, Canada', 'Venice, Los Angeles, CA, USA', 'Toronto, ON, Canada', 'Culver City, CA, USA', 'San Jose, CA, USA', 'Ringwood, NJ, USA', 'Hayward, CA, USA', 'San Mateo, CA, USA', 'Kitchener, ON, Canada', 'Berkeley, CA, USA', 'Menlo Park, CA, USA', 'Boulder, CO, USA', 'Sunnyvale, CA, USA', 'Dakar, Senegal', 'Milpitas, CA 95035, USA', 'Istanbul, Turkey', 'Los Gatos, CA, USA', 'Pleasanton, CA, USA', '555 Post St, San Francisco, CA 94102, USA', 'Hong Kong', 'Sacramento, CA, USA', 'Gainesville, FL, USA', 'Waterloo, ON, Canada', 'San Francisco Bay Area, CA, USA', 'Whitechapel, London, UK', 'Redwood Shores, Redwood City, CA, USA', 'Hamlin, NY, USA', 'San Antonio, TX, USA', 'Bengaluru, Karnataka, India', 'Silicon Valley, CA, USA', 'Oakland, CA, USA', 'Bothell, WA, USA', 'Honolulu, HI, USA', 'Shanghai, China', 'Makati, Metro Manila, Philippines', 'Kraków, Poland', 'Newport Beach, CA, USA', 'Virginia Beach, VA, USA', 'Fayetteville, AR, USA', 'Berlin, Germany', 'Rio de Janeiro, State of Rio de Janeiro, Brazil', 'Lehi, UT, USA', 'Victoria, BC, Canada', 'Ottawa, ON, Canada', 'Sterling, VA, USA', 'Tel Aviv-Yafo, Israel', 'Chattanooga, TN, USA', 'Ogden, UT, USA', 'Paris, France', 'San Leandro, CA, USA', 'Emeryville, CA, USA', 'Stanford, CA, USA', 'Hughson, CA 95326, USA', 'Everett, WA, USA', 'Austria', 'London, ON, Canada', 'Davis, CA, USA', 'San Diego, CA, USA', 'Amsterdam, Netherlands', 'Washington, DC, USA', 'Philadelphia, PA, USA', 'South San Francisco, CA, USA', 'Carlsbad, CA, USA', 'Foster City, CA, USA', 'Columbia, MO, USA', 'Singapore', 'Alameda, CA, USA', 'Niagara Falls, NY, USA', 'Troy, MI, USA', 'Madrid, Spain', 'Mexico City, CDMX, Mexico', 'Buenos Aires, Argentina', 'Beijing, China', 'Waterloo Regional Municipality, ON, Canada', 'McLean, VA, USA', 'Nashville, TN, USA', 'Las Vegas, NV, USA', 'Ljubljana, Slovenia', 'Reno, NV, USA', 'St. Louis, MO, USA', 'Bentonville, AR, USA', 'Jakarta, Indonesia', 'Gurugram, Haryana, India', 'Mumbai, Maharashtra, India', 'Dhaka, Bangladesh', 'Kathmandu 44600, Nepal', 'Kowloon City District, Hong Kong', 'Richmond, VA, USA', 'Indianapolis, IN, USA', 'Miami, FL, USA', 'Nairobi, Kenya', 'Silver Spring, MD, USA', 'Lagos, Nigeria', 'Durango, CO, USA', 'Bogotá, Bogota, Colombia', 'Centennial, CO, USA', 'Bihar, India', 'Pittsburgh, PA, USA', 'Hyderabad, Telangana, India', 'Cairo, Sidi Beshr Qebli, Montaza 1, Alexandria Governorate, Egypt', 'Oslo, Norway', 'Orlando, FL, USA', 'San Clemente, CA, USA', 'Newark, CA 94560, USA', 'Hoboken, NJ, USA', '2869 Glenview Ave, Los Angeles, CA 90039, USA', 'Detroit, MI, USA', '1316 W 11th St, Coffeyville, KS 67337, USA', 'Zapopan, Jalisco, Mexico', 'São José dos Campos, Sao Jose dos Campos - State of São Paulo, Brazil', 'Accra, Ghana', 'Santa Fe, NM, USA', 'Seoul, South Korea', 'Guadalajara, Jalisco, Mexico', 'Remote, OR 97458, USA', 'New Delhi, Delhi, India', 'Marina Del Rey, CA 90292, USA', 'Salt Lake City, UT, USA', 'Moscow, Russia', 'Fremont, CA, USA', 'Delhi, India', 'Oxford, UK', 'Monterrey, Nuevo Leon, Mexico', 'Cambridge, UK', 'Birmingham, AL, USA', 'Federal Capital Territory, Nigeria', 'Budapest, Hungary', 'Houston, TX, USA', 'Albany, NY, USA', 'United States', 'Hong Kong Island, Hong Kong', 'Casablanca, Morocco', 'Denver, CO, USA', 'Memphis, TN, USA', '620 S Aspen Ave, Broken Arrow, OK 74012, USA', 'Auckland, New Zealand', 'Walnut, CA, USA', 'Livermore, CA, USA', 'Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia', 'New Orleans, LA, USA', 'Brasilia - Federal District, Brazil', 'Johannesburg, South Africa', 'Tallinn, Estonia', 'Riga, Latvia', 'Surabaya, Surabaya City, East Java, Indonesia', 'Noida, Uttar Pradesh, India', 'Maastricht, Netherlands', 'Medellin, Antioquia, Colombia', 'LaBelle, FL 33935, USA', 'Westminster, London, UK', 'Dallas, TX, USA', 'Huntsville, AL, USA', 'Novato, CA, USA', 'Tempe, AZ, USA', 'Winslow St, Redwood City, CA 94063, USA', 'San Juan, Puerto Rico', 'Santiago, Santiago Metropolitan Region, Chile', 'Dubai - United Arab Emirates', 'Warsaw, Poland', 'Durham, NC, USA', 'Nantes, France', 'Mt Harwood, California 92358, USA', 'Santa Cruz, CA, USA', 'Cali, Valle del Cauca, Colombia', 'Seychelles', 'São Paulo, State of São Paulo, Brazil', 'Panama City, Panama', 'India', 'Erbil, Iraq', 'Lima, Peru', 'Chennai, Tamil Nadu, India', 'Richmond, CA, USA', 'Gothenburg, Sweden', 'Athens, Greece', 'Bellevue, WA, USA', 'Prague, Czechia', 'Idaho Falls, ID, USA', 'Munich, Germany', '201 E Jefferson St, Louisville, KY 40202, USA', 'Abuja, Nigeria', 'Rochester, MN, USA', 'Phoenix, AZ, USA', 'Ames, IA, USA', 'Van Nuys, Los Angeles, CA, USA', 'Kailua, HI, USA', 'Shenzhen, Guangdong, China', 'Kyiv, Ukraine, 02000', 'Kiel, Germany', 'Dublin, CA 94568, USA', 'Provo, UT, USA', "St. John's, NL, Canada", 'Cairo, Cairo Governorate, Egypt', 'Ventura, CA, USA', 'Taguig, Metro Manila, Philippines', 'Earth, TX 79031, USA', 'State College, PA, USA', 'Pasadena, CA, USA', 'Hamburg, Germany', 'Boise, ID, USA', 'Champaign, IL, USA', 'Melbourne VIC, Australia', 'Charlotte, NC, USA', 'Mesa, AZ, USA', 'Brisbane, CA, USA', 'Winston-Salem, NC, USA', 'Algeria', 'Little Rock, AR, USA', 'Charleston, SC, USA', 'Dar es Salaam, Tanzania', 'Lahore, Pakistan', 'North Bogor, Bogor City, West Java, Indonesia', 'Chandigarh, India', 'Kolkata, West Bengal, India', 'Cork, Ireland', 'East Palo Alto, CA, USA', 'Winnipeg, MB, Canada', 'Pune, Maharashtra, India', 'Recife - Paratibe, Recife - State of Pernambuco, Brazil', 'Medellín, Medellin, Antioquia, Colombia', 'Plymouth, MI 48170, USA', 'Burlington, MA, USA', 'Edmonton, AB, Canada', 'Belo Horizonte - State of Minas Gerais, Brazil', 'Irvine, CA, USA', 'Padua, Province of Padua, Italy', 'City of Knowledge, Panama City, Panama', 'Williamsburg, VA, USA', 'Providencia, Santiago Metropolitan Region, Chile', 'Burlington, VT, USA', '880 W Maude Ave, Sunnyvale, CA 94085, USA', 'New York, USA', 'Villanova, PA, USA', 'United Kingdom', 'Barcelona, Spain', 'Raleigh, NC, USA', 'Cleveland, OH, USA', 'Exeter, UK', 'Los Altos, CA, USA', 'Balneário Camboriú - State of Santa Catarina, Brazil', 'Hoàn Kiếm, Hanoi, Vietnam', 'Birmingham, UK', 'Aarhus, Denmark', 'Graz, Austria', 'Stuttgart, Germany', 'Manila, Metro Manila, Philippines', "Abidjan, Côte d'Ivoire", 'Vilnius, Lithuania', 'Zagreb, Croatia', 'Milan, Metropolitan City of Milan, Italy', 'North Kingstown, RI, USA', '12350 Pinecrest Rd, Reston, VA 20191, USA', 'Sunshine Coast QLD, Australia', 'Edinburgh, UK', 'Vienna, Austria', 'Barranquilla, Atlantico, Colombia', 'Ho Chi Minh City, Vietnam', 'Ontario, CA, USA', 'Fort Collins, CO, USA', 'Raipur, Chhattisgarh, India', 'Bandung, Bandung City, West Java, Indonesia', 'Orem, UT, USA', 'Omaha, NE, USA', 'St. Petersburg, FL, USA', 'Karachi, Pakistan', 'Walnut Creek, CA, USA', 'Brussels, Belgium', 'Calgary, AB, Canada', 'Glasgow, UK', 'Marlboro, VT, USA', '20 Pioneer Cres, Singapore 628555', 'Barranco, Peru', 'Coimbatore, Tamil Nadu, India', 'Windhoek, Namibia', 'Zürich, Switzerland', 'Sydney NSW, Australia', 'Maringá - Floriano, Maringá - State of Paraná, Brazil', 'Traverse City, MI, USA', 'Galway, Ireland', 'McKinney, TX, USA', 'Utrecht, Netherlands', 'Karachi City, Sindh, Pakistan', 'Helsinki, Finland', 'Córdoba, Cordoba, Argentina', 'Florida, USA', 'San Francisco Bay Trail, San Mateo, CA, USA', 'Tbilisi, Georgia', 'Fort Worth, TX, USA', 'Mérida, Yucatan, Mexico', 'Cape Town, South Africa', 'Truckee, CA 96161, USA', 'Brisbane QLD, Australia', 'Uberlândia, State of Minas Gerais, Brazil', 'Baltimore, MD, USA', 'Limerick, Ireland', 'Nicosia, Cyprus', 'Buffalo, NY, USA', 'Delaware City, DE, USA', 'São Carlos, SP, Brazil', 'Mill Valley, CA 94941, USA', 'Pereira, Risaralda, Colombia', 'Lusaka, Zambia', 'CA-1, San Francisco, CA, USA', 'San Francisco, San Diego, CA 92154, USA', 'Bucharest, Romania', 'Islamabad, Pakistan', 'Metro Manila, Philippines', 'Caracas, Capital District, Venezuela', 'Rochester, NY, USA', 'A Coruña, Spain', 'Quito, Ecuador', 'Mannheim, Germany', 'Wilmington, DE, USA', 'Addis Ababa, Ethiopia', 'Halifax Regional Municipality, NS, Canada', 'Toulouse, France', 'Hanoi, Hoàn Kiếm, Hanoi, Vietnam', 'Asheville, NC, USA', 'Maracaibo, Zulia, Venezuela', 'Manama, Bahrain', 'The Hague, Netherlands', 'Kampala, Uganda', 'Cyberjaya, Selangor, Malaysia', 'Lausanne, Switzerland', 'Ibadan, Nigeria', 'US-101, San Francisco, CA, USA', 'San José Province, San José, Costa Rica', 'Ecublens, Switzerland', '105102, Lagos, Nigeria', 'Claymont, DE 19703, USA', 'Royal Oak, MI, USA', 'Fredericton, NB, Canada', 'Nottingham, UK', 'Cancún, Quintana Roo, Mexico', '62 Shipeolu St, Somolu 102216, Lagos, Nigeria', 'Norwalk, CT, USA', 'Dayton, OH, USA', 'Gold Coast QLD, Australia', 'Huntington Beach, CA, USA', 'Cincinnati, OH, USA', 'Kirkland, WA, USA', 'Riyadh Saudi Arabia', 'Jeddah Saudi Arabia', 'Palm Beach Gardens, FL, USA', 'Long Beach, CA, USA', 'Lewes, DE 19958, USA', 'Grand Rapids, MI, USA', 'Carson, CA, USA', 'Tokyo, Japan', 'Monterey, CA, USA', 'Issaquah, WA, USA', 'Downers Grove, IL, USA', 'Winter Garden, FL 34787, USA', 'College Park, MD, USA', 'Potsdam, Germany', 'Hayes St, San Francisco, CA, USA', 'Woodland, CA, USA', 'Haifa, Israel', 'Surat, Gujarat, India', 'San Francisco – Oakland Bay Bridge, San Francisco – Oakland Bay Bridge, San Francisco, CA, USA', 'Manchester, UK', '548 Market St, San Francisco, CA 94104, USA', 'Temecula, CA, USA', 'Montpellier, France', '133 Kearny St, San Francisco, CA 94108, USA', 'Santa Barbara, CA, USA', 'Russian Hill Pl, San Francisco, CA 94133, USA', '156 2nd St, San Francisco, CA 94105, USA', '228 Park Ave S, New York, NY 10003, USA', 'Jersey City, NJ, USA', 'Kinshasa, Democratic Republic of the Congo', 'Broadway, New York, NY, USA', 'Dover, DE, USA', 'White Rock, BC, Canada', 'California St, San Francisco, CA, USA', 'Zug, Switzerland', 'Mission St, San Francisco, CA, USA', 'Roeland Dr, Roeland Park, KS 66205, USA', '303 Bedford Ave, Brooklyn, NY 11211, USA', 'Broad St, New York, NY, USA', '777 Tennessee St, San Francisco, CA 94107, USA', 'American Fork, UT 84003, USA', '2 Townsend St, San Francisco, CA 94107, USA', '15a Ajanaku St, Opebi, Ikeja 101233, Lagos, Nigeria', '1201 Tennessee St, San Francisco, CA 94107, USA', '380 Alabama St, San Francisco, CA 94110, USA', '800 Indiana St, San Francisco, CA 94107, USA', '2261 Market St #5744, San Francisco, CA 94114, USA', 'Curitiba, State of Paraná, Brazil', '815 W 1250 S, Orem, UT 84058, USA', '717 California St, San Francisco, CA 94108, USA', '793 S Van Ness Ave, San Francisco, CA 94110, USA', '205 W 76th St, New York, NY 10023, USA', 'Potrero Ave, San Francisco, CA, USA', '117 Quai de Valmy, 75010 Paris, France', 'El Segundo, CA, USA', 'Millbrae, CA, USA', 'Lake Oswego, OR, USA']

In [14]:
counts_of_unique_values = df['status'].value_counts()
print(counts_of_unique_values)

status
Active      3441
Inactive     805
Acquired     579
Public        19
Name: count, dtype: int64

In [199]:
df['teamSize'] = df['teamSize'].fillna(-1)
df['teamSize'] = df['teamSize'].astype(int)
df['teamSize'] = df['teamSize'].replace(-1, pd.NA)
counts_of_unique_values = df['teamSize'].value_counts()
print(counts_of_unique_values)
df.to_csv('data/companies.csv', index=False)

teamSize
2       1024
3        416
5        275
4        240
11       219
        ...
355        1
2400       1
211        1
540        1
87         1
Name: count, Length: 194, dtype: int64

In [167]:
nan_rows = df[df['slug'].isna()]  

display(nan_rows)

,Unnamed: 0,id,name,slug,website,smallLogoUrl,oneLiner,longDescription,teamSize,url,batch,status
158,158,382,Mixed Media Labs,NaN,NaN,NaN,NaN,NaN,<NA>,https://www.ycombinator.com/companies/382,W10,Inactive
606,606,599,Kuna Systems,NaN,http://getkuna.com,NaN,"We're making a smart, front door camera with i...",Stop break-ins before they happen. Kuna is the...,11,https://www.ycombinator.com/companies/599,W14,Acquired
1148,1148,1189,Sixa,NaN,https://sixa.io,NaN,Personal computer in the cloud,Sixa delivers a full computer that operates ri...,11,https://www.ycombinator.com/companies/1189,S16,Inactive

In [8]:
df = pd.read_csv('data/badges.csv')
print(df.shape)
df.head()

(2641, 3)

   Unnamed: 0   id           badge
0           0  379      topCompany
1           1  357      topCompany
2           2  356      topCompany
3           3  358  highlightWomen
4           4  383      topCompany

In [9]:
unique_counts = df.nunique()
print(unique_counts)

Unnamed: 0    2641
id            2143
badge            6
dtype: int64

In [10]:
nan_count_per_column = df.isna().sum()
print(nan_count_per_column)

Unnamed: 0    0
id            0
badge         0
dtype: int64

In [11]:
counts_of_unique_values = df['badge'].value_counts()
print(counts_of_unique_values)

badge
isHiring           1011
highlightWomen      732
highlightLatinx     487
highlightBlack      277
topCompany           91
nonprofit            43
Name: count, dtype: int64

In [43]:
df = pd.read_csv('data/industries.csv')
print(df.shape)
df.head()

(8838, 3)

   Unnamed: 0   id      industry
0           0  379      Consumer
1           1  379       Content
2           2  378           B2B
3           3  378  Productivity
4           4  375           B2B

In [44]:
unique_counts = df.nunique()
print(unique_counts)

Unnamed: 0    8838
id            4825
industry        57
dtype: int64

In [45]:
nan_count_per_column = df.isna().sum()
print(nan_count_per_column)

Unnamed: 0    0
id            0
industry      0
dtype: int64

In [34]:
counts_of_unique_values = df['industry'].value_counts()
print(counts_of_unique_values)

industry
B2B                                2325
Consumer                            799
Healthcare                          589
Fintech                             566
Engineering, Product and Design     483
Industrials                         269
Infrastructure                      211
Productivity                        190
Marketing                           135
Real Estate and Construction        132
Home and Personal                   127
Retail                              124
Analytics                           116
Healthcare IT                       114
Social                              114
Supply Chain and Logistics          114
Consumer Health and Wellness        114
Education                           114
Payments                            113
Finance and Accounting              111
Operations                          111
Content                             109
Sales                               103
Food and Beverage                    96
Security                             89
Human Resources                      84
Housing and Real Estate              79
Consumer Finance                     77
Banking and Exchange                 73
Credit and Lending                   72
Gaming                               68
Healthcare Services                  64
Recruiting and Talent                63
Manufacturing and Robotics           63
Therapeutics                         61
Diagnostics                          54
Climate                              52
Asset Management                     50
Apparel and Cosmetics                49
Aviation and Space                   44
Insurance                            44
Drug Discovery and Delivery          42
Medical Devices                      42
Consumer Electronics                 37
Construction                         36
Industrial Bio                       34
Legal                                33
Energy                               33
Government                           31
Travel, Leisure and Tourism          31
Agriculture                          26
Transportation Services              26
Office Management                    25
Virtual and Augmented Reality        21
Automotive                           20
Drones                               18
Job and Career Services              18
Name: count, dtype: int64

In [46]:
df = pd.read_csv('data/tags.csv')
print(df.shape)
df.head()

(12969, 3)

   Unnamed: 0   id             tag
0           0  379       Community
1           1  379    Social Media
2           2  379          Social
3           3  379  Social Network
4           4  378        Calendar

In [47]:
unique_counts = df.nunique()
print(unique_counts)

Unnamed: 0    12969
id             4463
tag             330
dtype: int64

In [48]:
nan_count_per_column = df.isna().sum()
print(nan_count_per_column)

Unnamed: 0    0
id            0
tag           0
dtype: int64

In [39]:
counts_of_unique_values = df['tag'].value_counts()
print(counts_of_unique_values)

tag
SaaS                       1046
B2B                         954
Fintech                     695
Artificial Intelligence     574
Developer Tools             466
                           ...
Lab-on-a-chip                 1
3D Printed Foods              1
Smart Locks                   1
Cyber Insurance               1
Swarm Robotics                1
Name: count, Length: 330, dtype: int64

In [21]:
df = pd.read_csv('data/regions.csv')
print(df.shape)
df.head()

(4844, 5)

,Unnamed: 0,id,region,country,address
0,0,379,America / Canada,United States of America,"San Francisco, CA, USA"
1,1,378,America / Canada,United States of America,"Cambridge, MA, USA"
2,2,375,America / Canada,United States of America,"San Francisco, CA, USA"
3,3,374,America / Canada,United States of America,"Redmond, WA, USA"
4,4,373,America / Canada,United States of America,"Mountain View, CA, USA"

In [58]:
unique_counts = df.nunique()
print(unique_counts)

Unnamed: 0    4844
id            4844
region          54
country         79
address        442
dtype: int64

In [59]:
nan_count_per_column = df.isna().sum()
print(nan_count_per_column)

Unnamed: 0      0
id              0
region        212
country       212
address       323
dtype: int64

In [61]:
counts_of_unique_values = df['address'].value_counts()
print(counts_of_unique_values)

address
San Francisco, CA, USA         1609
New York, NY, USA               442
London, UK                      130
Bengaluru, Karnataka, India     114
Los Angeles, CA, USA            108
                               ...
Winston-Salem, NC, USA            1
Algeria                           1
Little Rock, AR, USA              1
Dar es Salaam, Tanzania           1
Lake Oswego, OR, USA              1
Name: count, Length: 442, dtype: int64

In [210]:
founder_df = pd.read_csv('data/founders.csv')
companies_df = pd.read_csv('data/companies.csv')

company_slugs = companies_df['slug'].unique()
founder_df = founder_df[founder_df['company_slug'].isin(company_slugs)]

founder_df.to_csv('data/founders.csv', index=False)

In [211]:
df = pd.read_csv('data/founders.csv')
print(df.shape)
df.head()

(8426, 8)

,first_name,last_name,hnid,avatar_thumb,current_company,current_title,company_slug,top_company
0,Debanjum,Singh Solanky,110,https://bookface-images.s3.amazonaws.com/avata...,Khoj,NaN,khoj,False
1,Jon,Wade,__JW__,https://bookface-images.s3.amazonaws.com/avata...,NaN,NaN,union54,False
2,Sy,Bohy,__sy__,https://bookface-images.s3.amazonaws.com/avata...,Seam,NaN,seam,False
3,Abdelrahman,Hosny,_ahosny,https://bookface-images.s3.amazonaws.com/avata...,ShipBlu,NaN,shipblu,False
4,Christopher,Chae,_chrischae,https://bookface-images.s3.amazonaws.com/avata...,Relate,NaN,relate,False

In [212]:
unique_counts = df.nunique()
print(unique_counts)

first_name         3536
last_name          6178
hnid               8426
avatar_thumb       8190
current_company    4658
current_title       549
company_slug       4460
top_company           2
dtype: int64

In [213]:
nan_count_per_column = df.isna().sum()
print(nan_count_per_column)

first_name            4
last_name             9
hnid                  0
avatar_thumb          0
current_company     838
current_title      6227
company_slug          0
top_company           0
dtype: int64

In [214]:
counts_of_unique_values = df['company_slug'].value_counts()
print(counts_of_unique_values)

company_slug
tiptap             6
quindar            6
olark              6
ginkgo-bioworks    5
trackingplan       5
                  ..
keeling-labs       1
guac               1
current-foods      1
amulyte            1
sapling-ai         1
Name: count, Length: 4460, dtype: int64

In [215]:
prior_companies_df = pd.read_csv('data/prior_companies.csv')
founders_df = pd.read_csv('data/founders.csv')

founder_hnids = founders_df['hnid'].unique()
prior_companies_df = prior_companies_df[prior_companies_df['hnid'].isin(founder_hnids)]

prior_companies_df.to_csv('data/prior_companies.csv', index=False)

In [216]:
df = pd.read_csv('data/prior_companies.csv')
print(df.shape)
df.head()

(32510, 2)

     hnid    company
0     110       Khoj
1     110  Microsoft
2     110  Hillhacks
3  __JW__    Union54
4  __sy__       Seam

In [75]:
unique_counts = df.nunique()
print(unique_counts)

hnid        8465
company    19725
dtype: int64

In [76]:
nan_count_per_column = df.isna().sum()
print(nan_count_per_column)

hnid       0
company    0
dtype: int64

In [77]:
counts_of_unique_values = df['company'].value_counts()
print(counts_of_unique_values)

company
Google                                 419
Facebook                               223
Microsoft                              222
Amazon                                 126
Stanford University                    118
                                      ...
The Bell Policy Center                   1
Constar International                    1
Japan Exchange and Teaching Program      1
L2F                                      1
M&G                                      1
Name: count, Length: 19725, dtype: int64

In [220]:
schools_df = pd.read_csv('data/schools.csv')
founders_df = pd.read_csv('data/founders.csv')

founder_hnids = founders_df['hnid'].unique()
schools_df = schools_df[schools_df['hnid'].isin(founder_hnids)]

schools_df.to_csv('data/schools.csv', index=False)

In [221]:
df = pd.read_csv('data/schools.csv')
print(df.shape)
df.head()

(55115, 4)

,hnid,school,field_of_study,year
0,110,"Birla Institute of Technology and Science, Pilani",Electronics And Instrumentation,2009
1,110,"Birla Institute of Technology and Science, Pilani",Electronics And Instrumentation,2010
2,110,"Birla Institute of Technology and Science, Pilani",Electronics And Instrumentation,2011
3,110,"Birla Institute of Technology and Science, Pilani",Electronics And Instrumentation,2012
4,110,"Birla Institute of Technology and Science, Pilani",Electronics And Instrumentation,2013

In [222]:
unique_counts = df.nunique()
print(unique_counts)

hnid              7271
school            3581
field_of_study    3375
year               134
dtype: int64

In [223]:
nan_count_per_column = df.isna().sum()
print(nan_count_per_column)

hnid                 0
school               1
field_of_study    9044
year                 0
dtype: int64

In [224]:
counts_of_unique_values = df['hnid'].value_counts()
print(counts_of_unique_values)

hnid
jeffDef         202
brunolucas04     59
reidrubsamen     51
asamil           44
setpixel         43
               ...
Simonga25         1
simboben          1
sidneyrema        1
bviolante         1
stefanstokic      1
Name: count, Length: 7271, dtype: int64

In [225]:
null_field_mask = df['field_of_study'].isnull()

non_null_field = df[~null_field_mask].groupby(['hnid', 'school', 'field_of_study']).agg({'year': 'max'}).reset_index()

null_field = df[null_field_mask].groupby(['hnid', 'school']).agg({'year': 'max', 'field_of_study': 'first'}).reset_index()

preprocessed_df = pd.concat([non_null_field, null_field], ignore_index=True)

In [226]:
preprocessed_df.drop_duplicates(subset=['hnid', 'school', 'year'], inplace=True)

In [227]:
counts_of_unique_values = preprocessed_df['hnid'].value_counts()
print(counts_of_unique_values)

hnid
sriram_sandhya    9
nrudder           8
artem001          8
oparrott          8
tedleng           8
                 ..
jspiotti          1
jsun              1
jthomaslm         1
Patrick_C         1
joshuawright11    1
Name: count, Length: 7270, dtype: int64

In [228]:
preprocessed_df.to_csv('data/schools.csv', index=False)